name: Workflow for Codecov

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2 # Updated to v2 for better features including caching
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install root dependencies
        run: pnpm install

      - name: Install dependencies and setup Prisma
        run: |
          pnpm i --filter ./apps/...
          pnpm i --filter ./packages/...
          pnpm db:prisma 
        working-directory: .
      
      - name: Run tests and collect coverage
        run: |
          pnpm test --filter ./apps/... --recursive --if-present
          pnpm test --filter ./packages/... --recursive --if-present
        working-directory: .
        env:
          CI: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: UNLV-CS472-672/2024-S-GROUP3-Barbell
          directory: ./coverage/
          fail_ci_if_error: true
