name: Workflow for Codecov

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x 
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
          
      - name: Install root dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install dependencies and setup Prisma
        run: |
          pnpm i --filter ./apps/... --no-frozen-lockfile
          pnpm db:prisma 
        working-directory: .
      
      - name: Run tests and collect coverage
        run: |
          pnpm test --filter ./apps/... --recursive --if-present
          pnpm test --filter ./packages/... --recursive --if-present
        working-directory: .
        env:
          CI: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: UNLV-CS472-672/2024-S-GROUP3-Barbell
          directory: ./coverage/
          fail_ci_if_error: true
