name: Barbell Github Action

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['main']

jobs:
  # > Jobs 1
  build-n-coverage:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install root dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Setup Prisma Schema, Migrate, and Seed
        working-directory: .
        run: |
          cd packages/db && pnpm prisma generate && pnpm dotenv -e ../../.env prisma db push --force-reset && pnpm db:seed

      # - name: Run tests and collect coverage
      #   run: |
      #     pnpm run jest
      #   env:
      #     CI: true

      - name: Run tests in expo
        working-directory: .
        env:
          CI: true
        run: |
          cd apps/expo && pnpm run jest

      - name: Run tests in api
        working-directory: .
        env:
          CI: true
        run: |
          cd packages/api && pnpm run vitest

      - name: Upload expo coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: UNLV-CS472-672/2024-S-GROUP3-Barbell
          directory: ./apps/expo/jest-coverage/
          fail_ci_if_error: true

      - name: Upload api coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: UNLV-CS472-672/2024-S-GROUP3-Barbell
          directory: ./packages/api/vitest-coverage/
          fail_ci_if_error: true
